// combatantReducer related actions
export const ADD_COMBATANT_BLOCK = 'ADD_COMBATANT_BLOCK';
export const ADD_COMBATANT_TO_BLOCK = 'ADD_COMBATANT_TO_BLOCK';
export const INCREMENT_TURN = 'INCREMENT_TURN';
export const MODIFY_CURRENT_HP = 'MODIFY_CURRENT_HP';
export const HEAL_CURRENT_HP = 'HEAL_CURRENT_HP';
export const DAMAGE_CURRENT_HP = 'DAMAGE_CURRENT_HP';
export const RESET_TURN = 'RESET_TURN';

export const DELETE_COMBATANT_FROM_BLOCK = 'DELETE_COMBATANT_FROM_BLOCK';
export const DELETE_LAST_COMBATANT_FROM_BLOCK =
  'DELETE_LAST_COMBATANT_FROM_BLOCK';
