// combatantReducer related actions
export const ADD_COMBATANT_BLOCK = 'ADD_COMBATANT_BLOCK';
export const ADD_COMBATANT_TO_BLOCK = 'ADD_COMBATANT_TO_BLOCK';
export const INCREMENT_TURN = 'INCREMENT_TURN';
export const REMOVE_COMBATANT_FROM_BLOCK = 'REMOVE_COMBATANT_FROM_BLOCK';
export const MODIFY_CURRENT_HP = 'MODIFY_CURRENT_HP';
// export const ADD_COMBATANT_TO_BLOCK = 'ADD_COMBATANT_TO_BLOCK';
